name: Get Changed Files
on:
  pull_request:
    branches:
      - main
    paths: 
      - '.github/workflows/*.yml'
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
          fetch-depth: 2
      - name: display
        run: echo "$(git diff --name-only origin/main origin/${GITHUB_HEAD_REF})"
