name: Get Changed Files
on:
  pull_request:
    branches:
      - main
    paths: 
      - '.github/workflows/*.yml'
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - name: display
        run: echo "$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
