name: Get Changed Files
on:
  pull_request:
    branches:
      - main
    paths: 
      - '.github/workflows/*.yml'
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
          fetch-depth: 0
      # git diff --name-only HEAD^ HEAD -> get the different files of source branch (changed-files) with parent of source branch (main)
      - name: display
        run: |
          echo "${{ github.event.pull_request.base.sha }}"
          echo "${{ github.event.pull_request.head.sha }}"
          echo "$(git rev-parse HEAD^)"
          echo "$(git rev-parse HEAD)"
