name: on-merge-branch
run-name: ${{ github.actor }} merged PR from test
on:
  pull_request:
    types:
      - closed
    branches:
      - 'test'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo test PR was merged