name: on-merge-branch
run-name: ${{ github.actor }} merged PR from */add-metric
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && contains(github.head_ref, '/add-metric')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR from */add-metric was merged