name: Continuous Integration
on:
  push:
    branches:
      - main
    # Ignore changes in folders that are affected by the auto commit. (Node.js project)
    paths-ignore: 
      - '*.txt'
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  build:
    # if: contains(github.head_ref, '/add-metric')
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
    
    - name: Set environment variable "is-valid-branch"
      if: contains(github.head_ref, '/add-metric')
      run: echo "is-valid-branch=true" >> $GITHUB_ENV

    # Build steps
    - name: Make txt file
      if: github.event_name == 'push' && env.is-valid-branch == true
      run: |
        echo "Branch name = ${{ github.head_ref }}"
        echo This is sample text > MyFile6.txt

    # Commit and push all changed files. 
    # Must only affect files that are listed in "paths-ignore".
    - name: GIT Commit Build Artifacts (MyFile.txt)
      # Only run on main branch push (e.g. pull request merge).
      if: github.event_name == 'push' && env.is-valid-branch == true
      run: |
        echo "Branch name = ${{ github.head_ref }}"
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git add *.txt
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push