name: On Push to Branch
on:
  pull_request:
    branches:
      - main
    paths: 
      - '.github/workflows/*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  build:
    # if: contains(github.head_ref, '/add-metric')
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: '[auto] Push to Main Build Artifacts'
      CI_COMMIT_AUTHOR: Push to Main
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
        fetch-depth: 0

    - name: Check if any *.yaml changes were made since last auto-commit
      run: |
        count=0
        message="$(git log -1 --pretty=format:'%s' HEAD)"
        author="$(git log -1 --pretty=format:'%an' HEAD)"
        
        is_auto_commit="false"
        if { [ "$message" == "${{ env.CI_COMMIT_MESSAGE }}" ] && [ "$author" == "${{ env.CI_COMMIT_AUTHOR }}" ]; }
        then
          echo "No YAML changes were made since the last auto-commit! No DAGs will be generated..."
          is_auto_commit="true"
        fi

        while [ "$is_auto_commit" == "false" ]
        do
          echo "List of files changed in commit $(git log -1 --pretty=format:'%h' HEAD~$((count)))"
          echo -e "$(git diff --name-only --line-prefix=`git rev-parse --show-toplevel`/ HEAD~$((count+1)) HEAD~$((count)))\n"

          if [[ "$(git diff --name-only --line-prefix=`git rev-parse --show-toplevel`/ HEAD~$((count+1)) HEAD~$((count)) | grep .yml$)" != "" ]];
          then
            echo "Detected YAML changes! DAGs will be generated..."
            echo "generate-dags=true" >> $GITHUB_ENV
            break
          fi

          count=$((count+1))
          message="$(git log -1 --pretty=format:'%s' HEAD~$((count)))"
          author="$(git log -1 --pretty=format:'%an' HEAD~$((count)))"

          if { [ "$message" == "${{ env.CI_COMMIT_MESSAGE }}" ] && [ "$author" == "${{ env.CI_COMMIT_AUTHOR }}" ]; }
          then
            echo "No YAML changes were made since the last auto-commit! No DAGs will be generated..."
            is_auto_commit="true"
          fi
        done

    # Set environment variable "is-auto-commit" 
    # - name: Set environment variable "is-auto-commit"
    #   if: github.event.commits[0].message == env.CI_COMMIT_MESSAGE && github.event.commits[0].author.name == env.CI_COMMIT_AUTHOR
    #   run: echo "is-auto-commit=true" >> $GITHUB_ENV

    # Commit and push all changed files. 
    # Must only affect files that are listed in "paths-ignore".
    - name: GIT Commit Build Artifacts
      # Only run on main branch push (e.g. pull request merge).
      if: env.generate-dags == 'true'
      run: |
        echo This is sample text > hello4.txt
        if [[ "$(git status -s)" != "" ]];
        then
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add .
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
        fi